---

# - name: Download Meslo font
#   get_url:
#     url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/Meslo.zip
#     dest: /tmp/Meslo.zip
# 
# - name: Create nerds font dir
#   file:
#     path: /usr/local/share/fonts/nerd/Meslo
#     state: directory
#     mode: '0755'
# 
# - name: Extract Meslo font
#   unarchive:
#     src: /tmp/Meslo.zip
#     dest: /usr/local/share/fonts/nerd/Meslo
# 
# - name: 'Fonts | Debian | Update APT cache.'
#   become: yes
#   apt:
#     update_cache: yes
# 
- name: Add zsh and git
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - zsh
    - zsh-autosuggestions  # https://github.com/zsh-users/zsh-autosuggestions
    - zsh-syntax-highlighting  # https://github.com/zsh-users/zsh-syntax-highlighting
    - git

      # zplug ?
      # https://github.com/zplug/zplug

- name: Add fzf, bat, ranger and ag
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - fzf
    - fd-find  # find alternative https://github.com/sharkdp/fd
    - htop  # interactive text-mode process viewer https://github.com/hishamhm/htop
    - bat  # cat with wings https://github.com/sharkdp/bat
    - ranger  # ranger shell https://github.com/ranger/ranger
    - silversearcher-ag  # https://github.com/ggreer/the_silver_searcher
    # - exuberant-ctags  # http://ctags.sourceforge.net/


    # Other fuzzy finder
    # https://github.com/jhawthorn/fzy
    # https://github.com/mooz/percol
    # https://github.com/peco/peco

- name: Add ripgrep from github
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb


    #  - name: Add googler from github
    #    apt:
    #      deb: https://github.com/jarun/googler/releases/download/v3.9/googler_3.9-1_ubuntu18.04.amd64.deb
    #

- name: Install zsh-z
  git:
    repo: 'https://github.com/agkozak/zsh-z.git'
    dest: '/usr/local/share/zsh-z'
    clone: yes
    update: yes


#- name: Install zsh theme powerlevel10k
#  git:
#    repo: https://github.com/romkatv/powerlevel10k.git
#    dest: /usr/local/share/powerlevel10k
#    depth: 1
#    clone: yes
#    update: yes
#


- name: Install zsh completion files for MongoDB 3.6 server & tools
  git:
    repo: https://github.com/JamesKovacs/zsh_completions_mongodb.git
    dest: /usr/local/share/zsh_completions_mongodb
    depth: 1
    clone: yes
    update: yes


- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes


  # - name: Replace a localhost entry with our own
  #   lineinfile:
  #     path: /etc/hosts
  #     regexp: '^127\.0\.0\.1'
  #     line: 127.0.0.1 localhost
  #     owner: root
  #     group: root
  #     mode: '0644'
